name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    env:
      # Optional env for react-native-config; add more via repository secrets if needed
      APP_NAME: StorefrontApp
      APP_IDENTIFIER: com.storefront.app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'yarn'

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile || yarn install

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Assemble Debug APK
        working-directory: android
        run: ./gradlew :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Decode release keystore
        if: ${{ secrets.ANDROID_KEYSTORE_B64 != '' }}
        run: |
          mkdir -p android/app
          echo "${{ secrets.ANDROID_KEYSTORE_B64 }}" | base64 -d > android/app/release.keystore

      - name: Assemble Release AAB
        if: ${{ secrets.ANDROID_KEYSTORE_B64 != '' }}
        working-directory: android
        env:
          ANDROID_STOREFRONT_APP_UPLOAD_STORE_FILE: ${{ github.workspace }}/android/app/release.keystore
          ANDROID_STOREFRONT_APP_UPLOAD_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_STOREFRONT_APP_UPLOAD_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_STOREFRONT_APP_UPLOAD_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: ./gradlew :app:bundleRelease

      - name: Upload Release AAB
        if: ${{ secrets.ANDROID_KEYSTORE_B64 != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab

